### ISSUE TITLE
Ember 2.1.0 Registry Deprecation

### ISSUE THREAD

**Issue by gerry3** [ember-data/active-model-adapter#58]
In `app/instance-initializers/active-model-adapter.js`, both:

```
registry.register('adapter:-active-model', ActiveModelAdapter);
registry.register('serializer:-active-model', ActiveModelSerializer);
```

log this deprecation in Ember 2.1.0:

> DEPRECATION: Using `ApplicationInstance.registry.register` is deprecated. Please use `ApplicationInstance.register` instead. [deprecation id: ember-application.app-instance-registry] See http://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry for more details.

**Comment by bmac** [comment]
I believe this is fixed by https://github.com/ember-data/active-model-adapter/pull/60

**Comment by dzbo** [comment]
For me I'm still having this deprecation. 2.0.1 version still uses `registry.register` althought master branch has this fix.
